/// Flutter icons Dogemate
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Dogemate
///      fonts:
///       - asset: fonts/Dogemate.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Dogemate {
  Dogemate._();

  static const _kFontFam = 'Dogemate';
  static const String? _kFontPkg = null;

  static const IconData arrow_next_ios = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back_ios = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_back_generic = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_current = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_near = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData image = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dogemate = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rewind = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nein = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData love = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dots = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_down = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dog = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shield = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_next_generic = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData contact = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
